services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    networks: 
      - app-network
    ports:
      - "1883:1883"
      - "9001:9001"
    user: "${UID}:${GID}"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/http:/mosquitto/http
  
  nginx:
    container_name: nginx
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app-network
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    networks:
      - app-network
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - mosquitto

networks:
  app-network:
    driver: bridge
