services:
  splashflag:
    container_name: splashflag
    image: splashflag:latest  # Replace with your actual image
    networks:
      - app-network

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    networks: 
      - app-network
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    networks:
      - app-network
    command: tunnel run --token $CLOUDFLARE_TUNNEL_TOKEN
    depends_on:
      - splashflag
      - mosquitto

networks:
  app-network:
    driver: bridge

volumes:
  - mosquitto_config:
  - mosquitto_data:
  - mosquitto_log: